name: Lumberjack CI

on:
  pull_request:
    types: [opened]
  push:
  release:
    types: [published]

jobs:
  build:
    runs-on: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Gradle Build
        run: ./gradlew build
  publish:
    runs-on: [ubuntu-latest]
    needs: build
    if: ${{ github.event_name == 'release' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Gradle Publish
        run: ./gradlew bintrayPublish
